language: go
go:
- 1.12.5
install:
- go get golang.org/x/tools/cmd/cover
- go get -v github.com/axw/gocov/gocov
- go get -v github.com/mattn/goveralls
script:
- GO111MODULE=on go test -race -v -covermode=atomic -coverprofile=profile_tmp github.com/getlantern/http-proxy/server && tail -n +2 profile_tmp >> profile.cov && tail -n +2 profile_tmp >> profile.cov
after_success:
- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
