language: go
go:
- 1.4.3
install:
- go get golang.org/x/tools/cmd/cover
- go get -v github.com/axw/gocov/gocov
- go get -v github.com/mattn/goveralls
script:
- go test -v -covermode=count -coverprofile=profile *.go
after_success:
- GOPATH=`pwd`:$GOPATH $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
